services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=muser
      - MONGO_INITDB_ROOT_PASSWORD=mpass
    ports:
      - "27017:27017"
  web:
    build: .
    command: python -u app.py
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://muser:mpass@db:27017/users
