services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=user_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://db:27017/user_db  
    depends_on:
      - db
