version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  web:
    build: .
    container_name: flask-app
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/users
    depends_on:
      - mongo

volumes:
  mongo-data:
